### ISSUE TITLE
Fail to build with multiple --ghc-options options

### ISSUE THREAD

**Issue by DouglasRaillard** [ekmett/distributive#57] opened 2020-10-19 10:18 UTC
Hi,

It seems that passing multiple options to stack build --ghc-options fails, whereas it's working for most other packages:

```
$ stack build "--ghc-options=-O2 -fno-prof-auto" distributive                                           
distributive> configure
distributive> ghc: on the commandline: malformed integer argument in -O2 -fno-prof-auto
distributive> Usage: For basic information, try the `--help' option.

--  While building package distributive-0.6.2 using:
      /home/raillard/.stack/programs/x86_64-linux/ghc-tinfo6-8.10.2/bin/ghc-8.10.2 --make -odir /tmp/stack-0ae05188c22eabac/distributive-0.6.2/.stack-work/dist/x86_64-linux-tinfo6/Cabal-3.2.0.0/setup -hidir /tmp/stack-0ae05188c22eabac/distributive-0.6.2/.stack-work/dist/x86_64-linux-tinfo6/Cabal-3.2.0.0/setup -i -i. -clear-package-db -global-package-db -package-db=/home/raillard/.stack/snapshots/x86_64-linux-tinfo6/bd049dcf740078ef9397dcd2216c57741174e6feb027795f55a0d00361558ef0/8.10.2/pkgdb -package-db=/home/raillard/Documents/Douglas/Programmation/Haskell/ftrace/.stack-work/install/x86_64-linux-tinfo6/bd049dcf740078ef9397dcd2216c57741174e6feb027795f55a0d00361558ef0/8.10.2/pkgdb -hide-all-packages -package-id=Cabal-3.2.0.0 -package-id=base-4.14.1.0 -package-id=cabal-doctest-1.0.8-8FuiLtyYbOyAYReyoJWbHo -optP-include -optP/tmp/stack-0ae05188c22eabac/distributive-0.6.2/.stack-work/dist/x86_64-linux-tinfo6/Cabal-3.2.0.0/setup/setup_macros.h /tmp/stack-0ae05188c22eabac/distributive-0.6.2/Setup.lhs /home/raillard/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs -main-is StackSetupShim.mainOverride -o /tmp/stack-0ae05188c22eabac/distributive-0.6.2/.stack-work/dist/x86_64-linux-tinfo6/Cabal-3.2.0.0/setup/setup -threaded -O2 "-O2 -fno-prof-auto"
    Process exited with code: ExitFailure 1
```

If only one option is passed, e.g. `--ghc-options=-O2 ` (or any other), it seems to work. I'm not sure if it's a stack issue or a distributive issue, but it's the only package I've seen with that behavior so I'm assuming the latter.

Versions:
stack: Version 2.3.1, Git revision de2a7b694f07de7e6cf17f8c92338c16286b2878 (dirty) (8103 commits) x86_64
distributive-0.6.2

**Comment by RyanGlScott** [comment] 2020-10-19 10:51
I'm afraid that I can't reproduce this. I downloaded `stack` using the instructions [here](https://docs.haskellstack.org/en/stable/README/) (`curl -sSL https://get.haskellstack.org/ | sh`), and then ran the command above, which appeared to work without issue:

<details>

```
$ stack --version
Version 2.5.1, Git revision d6ab861544918185236cf826cb2028abb266d6d5 x86_64 hpack-0.33.0

$ stack build "--ghc-options=-O2 -fno-prof-auto" distributive
Writing implicit global project config file to: /home/rgscott/.stack/global-project/stack.yaml
Note: You can change the snapshot via the resolver field there.
Using latest snapshot resolver: lts-16.19
Preparing to install GHC to an isolated location.
This will not interfere with any system-level installation.
Downloaded ghc-8.8.4.
Installed GHC.
[1 of 2] Compiling Main             ( /home/rgscott/.stack/setup-exe-src/setup-mPHDZzAJ.hs, /home/rgscott/.stack/setup-exe-src/setup-mPHDZzAJ.o )
[2 of 2] Compiling StackSetupShim   ( /home/rgscott/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs, /home/rgscott/.stack/setup-exe-src/setup-shim-mPHDZzAJ.o )
Linking /home/rgscott/.stack/setup-exe-cache/x86_64-linux/tmp-Cabal-simple_mPHDZzAJ_3.0.1.0_ghc-8.8.4 ...
base-orphans > configure
base-orphans > Configuring base-orphans-0.8.3...
base-orphans > build
cabal-doctest> configure
base-orphans > Preprocessing library for base-orphans-0.8.3..
base-orphans > Building library for base-orphans-0.8.3..
base-orphans > [1 of 2] Compiling Data.Orphans.Prelude
base-orphans > [2 of 2] Compiling Data.Orphans
cabal-doctest> Configuring cabal-doctest-1.0.8...
cabal-doctest> build
tagged       > configure
cabal-doctest> Preprocessing library for cabal-doctest-1.0.8..
cabal-doctest> Building library for cabal-doctest-1.0.8..
cabal-doctest> [1 of 1] Compiling Distribution.Extra.Doctest
tagged       > Configuring tagged-0.8.6...
tagged       > build
tagged       > Preprocessing library for tagged-0.8.6..
tagged       > Building library for tagged-0.8.6..
tagged       > [1 of 2] Compiling Data.Proxy.TH
tagged       > [2 of 2] Compiling Data.Tagged
cabal-doctest> copy/register
cabal-doctest> Installing library in /home/rgscott/.stack/snapshots/x86_64-linux/25ae295514e13f35d8e237cc1e1c1ca4050f5bfd7d764fb6da49e3c47519c242/8.8.4/lib/x86_64-linux-ghc-8.8.4/cabal-doctest-1.0.8-2wQRz9ec1yB5lMDRmEgBWB
cabal-doctest> Registering library for cabal-doctest-1.0.8..
tagged       > copy/register
tagged       > Installing library in /home/rgscott/.stack/snapshots/x86_64-linux/25ae295514e13f35d8e237cc1e1c1ca4050f5bfd7d764fb6da49e3c47519c242/8.8.4/lib/x86_64-linux-ghc-8.8.4/tagged-0.8.6-LfhHZ57rMjK9JkdnSRh9cF
tagged       > Registering library for tagged-0.8.6..
base-orphans > copy/register
base-orphans > Installing library in /home/rgscott/.stack/snapshots/x86_64-linux/25ae295514e13f35d8e237cc1e1c1ca4050f5bfd7d764fb6da49e3c47519c242/8.8.4/lib/x86_64-linux-ghc-8.8.4/base-orphans-0.8.3-AvdqrlXOqa9JJLYVNDAuKk
base-orphans > Registering library for base-orphans-0.8.3..
distributive > configure
distributive > [1 of 2] Compiling Main             ( /tmp/stack-de4c3ca458406cfd/distributive-0.6.2/Setup.lhs, /tmp/stack-de4c3ca458406cfd/distributive-0.6.2/.stack-work/dist/x86_64-linux/Cabal-3.0.1.0/setup/Main.o )
distributive > [2 of 2] Compiling StackSetupShim   ( /home/rgscott/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs, /tmp/stack-de4c3ca458406cfd/distributive-0.6.2/.stack-work/dist/x86_64-linux/Cabal-3.0.1.0/setup/StackSetupShim.o )
distributive > Linking /tmp/stack-de4c3ca458406cfd/distributive-0.6.2/.stack-work/dist/x86_64-linux/Cabal-3.0.1.0/setup/setup ...
distributive > Configuring distributive-0.6.2...
distributive > build
distributive > Preprocessing library for distributive-0.6.2..
distributive > Building library for distributive-0.6.2..
distributive > [1 of 2] Compiling Data.Distributive
distributive > [2 of 2] Compiling Data.Distributive.Generic
distributive > copy/register
distributive > Installing library in /home/rgscott/.stack/snapshots/x86_64-linux/25ae295514e13f35d8e237cc1e1c1ca4050f5bfd7d764fb6da49e3c47519c242/8.8.4/lib/x86_64-linux-ghc-8.8.4/distributive-0.6.2-HNxB7q7VKYc2kUt6n1c8wI
distributive > Registering library for distributive-0.6.2..
Completed 4 action(s).
```
</details>

Perhaps this is a bug in an older version of `stack`, which you are using?

**Comment by DouglasRaillard** [comment] 2020-10-19 14:00
I just tried with a bleeding edge stack [1], and the issue is still the same. Maybe it's something else that the installer does other than just the stack binary, I'm not sure (I'm installing stack with the package manager of my distro).

Also, I used `--stack-root` pointed at an empty folder to make sure there is no interference with whatever could have been built before. Could you try this as well so we can rule out any stateful weirdness ?

[1] Version 2.6.0, Git revision 9621945bf7fe6d0a526ee6b6f183d3c821143979 (8254 commits) PRE-RELEASE x86_64 hpack-0.33.0

**Comment by phadej** [comment] 2020-10-19 14:46
I tried with both

```
Version 2.5.1, Git revision d6ab861544918185236cf826cb2028abb266d6d5 x86_64 hpack-0.33.0
Version 2.6.0, Git revision 9621945bf7fe6d0a526ee6b6f183d3c821143979 PRE-RELEASE x86_64 hpack-0.33.0
```

and couldn't reproduce this.

I see

```
[debug] Process finished in 553ms: /codetmp/distributive-0.6.2/.stack-work/dist/x86_64-linux/Cabal-3.0.1.0/setup/setup ... --ghc-options "-O2 -fno-prof-auto"
```

in output. That is wrong. I don't know what is `stack` command line interface contract is, should it split this arguments or not.

With separate flags:

```
stack build --ghc-options=-O2 --ghc-options=-fno-prof-auto distributive -v
```

same debug output is

```
[debug] Process finished in 543ms: /codetmp/distributive-0.6.2/.stack-work/dist/x86_64-linux/Cabal-3.0.1.0/setup/setup ... --ghc-options -O2 --ghc-options -fno-prof-auto
```

Why GHC doesn't fail on my and Ryan machine, I don't know. Whether it's really more of `stack` command line interface issue, I do think so.

**Comment by RyanGlScott** [comment] 2020-10-19 14:47
> Also, I used `--stack-root` pointed at an empty folder to make sure there is no interference with whatever could have been built before. Could you try this as well so we can rule out any stateful weirdness ?

I tried `mkdir emptydir && stack --stack-root $(pwd)/emptydir build "--ghc-options=-O2 -fno-prof-auto" distributive`, but it still succeeded.

I agree with @phadej's assessment that the use of `"-O2 -fno-prof-auto"` is very suspicious, and I'm leaning on the side of this being a `stack` bug.

**Comment by phadej** [comment] 2020-10-19 14:54
For the reference, in fact `Cabal` should split on spaces (see `splitArgs`). Yet I'd recommend to be more explicit, and pass arguments one by one with `--ghc-option` (singular). https://github.com/haskell/cabal/blob/b32799f13f9665cbfe598b62cbe31a7fa8f6fe74/Cabal/src/Distribution/Simple/Setup.hs#L2102-L2146

**Comment by phadej** [comment] 2020-10-19 14:57
I found why it doesn't fail.

By default, GHC just warns about unrecognized flags;

```
on the commandline: warning:
    unrecognised warning flag: -Wall -Wextra
```

@DouglasRaillard probably has some pedantic flag which turns that into error.

**Comment by DouglasRaillard** [comment] 2020-10-19 15:12
Ok, I think I found the culprit `apply-ghc-options`:

```
#! /bin/bash

mkdir build && cd build
mkdir stack-root
stack_root=$(readlink -f stack-root)

stack unpack "--stack-root=$stack_root" distributive
mv distributive-0.6.2 distributive

cat > stack.yaml << EOF
resolver: nightly-2020-10-14
packages:
- ./distributive/

apply-ghc-options: everything
EOF

stack build "--stack-root=$stack_root" "--ghc-options=-O2 -fno-prof-auto" .
```
Now the question is why is it breaking distributive but no other package ? I unfortunately cannot really avoid using it since stack otherwise ignores -fno-prof-auto and I end up with 6x slow down, along with a useless profiling report cluttered with >>=

I tried passing --ghc-options one by one and it seems to work indeed, thanks for the suggestion. Maybe I should open a ticket on stack to ask for a documentation change. They rely on word splitting in the documentation:
https://docs.haskellstack.org/en/stable/GUIDE/#ghc-options

**Comment by RyanGlScott** [comment] 2020-10-28 10:57
> Maybe I should open a ticket on stack to ask for a documentation change.

That would be my recommendation, yes.

**Comment by RyanGlScott** [comment] 2020-11-28 18:03
Closing in favor of commercialhaskell/stack#5418.

**Closed by RyanGlScott** 2020-11-28 18:03 UTC
Labels: build-system, can't duplicate
